name: Norminette Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar a Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip3 install norminette==3.3.50

      - name: Rodar a Norminette com flags
        run: |
          norminette minishell/ -R CheckForbiddenSourceHeader

